// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: visual_plan.proto

package tipb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	_ "github.com/gogo/protobuf/gogoproto"

	encoding_binary "encoding/binary"

	io "io"

	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VisualData struct {
	// the name of the current operator
	Name string `protobuf:"bytes,1,req,name=name" json:"name"`
	// the cost of the current operator
	//  for "visual analyze stmt" or slow queries: cost means real cost
	//  for "visual stmt": cost means est_cost
	Cost    float64 `protobuf:"fixed64,2,req,name=cost" json:"cost"`
	EstRows float64 `protobuf:"fixed64,3,req,name=est_rows,json=estRows" json:"est_rows"`
	ActRows uint64  `protobuf:"varint,4,req,name=act_rows,json=actRows" json:"act_rows"`
	// The reader may use this
	AccessTable     string `protobuf:"bytes,5,req,name=access_table,json=accessTable" json:"access_table"`
	AccessIndex     string `protobuf:"bytes,6,req,name=access_index,json=accessIndex" json:"access_index"`
	AccessPartition string `protobuf:"bytes,7,req,name=access_partition,json=accessPartition" json:"access_partition"`
	// The time spent by the current operator
	TimeUs float64 `protobuf:"fixed64,8,req,name=time_us,json=timeUs" json:"time_us"`
	// The current operator run at root/cop[tikv]/cop[tiflash]/cop[tidb]
	RunAt string `protobuf:"bytes,9,req,name=run_at,json=runAt" json:"run_at"`
	// The children of the current operator
	Children         []*VisualData `protobuf:"bytes,10,rep,name=children" json:"children,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *VisualData) Reset()                    { *m = VisualData{} }
func (m *VisualData) String() string            { return proto.CompactTextString(m) }
func (*VisualData) ProtoMessage()               {}
func (*VisualData) Descriptor() ([]byte, []int) { return fileDescriptorVisualPlan, []int{0} }

func (m *VisualData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VisualData) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *VisualData) GetEstRows() float64 {
	if m != nil {
		return m.EstRows
	}
	return 0
}

func (m *VisualData) GetActRows() uint64 {
	if m != nil {
		return m.ActRows
	}
	return 0
}

func (m *VisualData) GetAccessTable() string {
	if m != nil {
		return m.AccessTable
	}
	return ""
}

func (m *VisualData) GetAccessIndex() string {
	if m != nil {
		return m.AccessIndex
	}
	return ""
}

func (m *VisualData) GetAccessPartition() string {
	if m != nil {
		return m.AccessPartition
	}
	return ""
}

func (m *VisualData) GetTimeUs() float64 {
	if m != nil {
		return m.TimeUs
	}
	return 0
}

func (m *VisualData) GetRunAt() string {
	if m != nil {
		return m.RunAt
	}
	return ""
}

func (m *VisualData) GetChildren() []*VisualData {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*VisualData)(nil), "tipb.VisualData")
}
func (m *VisualData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VisualData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.Name)))
	i += copy(dAtA[i:], m.Name)
	dAtA[i] = 0x11
	i++
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Cost))))
	i += 8
	dAtA[i] = 0x19
	i++
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.EstRows))))
	i += 8
	dAtA[i] = 0x20
	i++
	i = encodeVarintVisualPlan(dAtA, i, uint64(m.ActRows))
	dAtA[i] = 0x2a
	i++
	i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.AccessTable)))
	i += copy(dAtA[i:], m.AccessTable)
	dAtA[i] = 0x32
	i++
	i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.AccessIndex)))
	i += copy(dAtA[i:], m.AccessIndex)
	dAtA[i] = 0x3a
	i++
	i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.AccessPartition)))
	i += copy(dAtA[i:], m.AccessPartition)
	dAtA[i] = 0x41
	i++
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.TimeUs))))
	i += 8
	dAtA[i] = 0x4a
	i++
	i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.RunAt)))
	i += copy(dAtA[i:], m.RunAt)
	if len(m.Children) > 0 {
		for _, msg := range m.Children {
			dAtA[i] = 0x52
			i++
			i = encodeVarintVisualPlan(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintVisualPlan(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *VisualData) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	n += 1 + l + sovVisualPlan(uint64(l))
	n += 9
	n += 9
	n += 1 + sovVisualPlan(uint64(m.ActRows))
	l = len(m.AccessTable)
	n += 1 + l + sovVisualPlan(uint64(l))
	l = len(m.AccessIndex)
	n += 1 + l + sovVisualPlan(uint64(l))
	l = len(m.AccessPartition)
	n += 1 + l + sovVisualPlan(uint64(l))
	n += 9
	l = len(m.RunAt)
	n += 1 + l + sovVisualPlan(uint64(l))
	if len(m.Children) > 0 {
		for _, e := range m.Children {
			l = e.Size()
			n += 1 + l + sovVisualPlan(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovVisualPlan(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozVisualPlan(x uint64) (n int) {
	return sovVisualPlan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VisualData) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVisualPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VisualData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VisualData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Cost = float64(math.Float64frombits(v))
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field EstRows", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.EstRows = float64(math.Float64frombits(v))
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActRows", wireType)
			}
			m.ActRows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActRows |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessTable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessTable = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000010)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000020)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessPartition", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessPartition = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000040)
		case 8:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUs", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.TimeUs = float64(math.Float64frombits(v))
			hasFields[0] |= uint64(0x00000080)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000100)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Children", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Children = append(m.Children, &VisualData{})
			if err := m.Children[len(m.Children)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVisualPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVisualPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000080) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000100) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVisualPlan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVisualPlan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthVisualPlan
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowVisualPlan
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipVisualPlan(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthVisualPlan = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVisualPlan   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("visual_plan.proto", fileDescriptorVisualPlan) }

var fileDescriptorVisualPlan = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0x80, 0xd7, 0xae, 0xfb, 0xcb, 0x04, 0x67, 0x50, 0x08, 0x8a, 0x5d, 0xf1, 0xc6, 0x0a, 0xd2,
	0x81, 0x6f, 0xe0, 0xf0, 0xc6, 0xbb, 0x31, 0xd4, 0xdb, 0x72, 0x96, 0x85, 0x19, 0xe8, 0x92, 0xd2,
	0x9c, 0x3a, 0x1f, 0xc5, 0x47, 0xda, 0xa5, 0x4f, 0x20, 0x32, 0x1f, 0xc0, 0x57, 0x90, 0xb4, 0xab,
	0x06, 0xbc, 0x0b, 0xdf, 0xf7, 0x9d, 0x84, 0x1c, 0x72, 0xf4, 0x22, 0x4d, 0x09, 0x59, 0x9a, 0x67,
	0xa0, 0x92, 0xbc, 0xd0, 0xa8, 0x69, 0x80, 0x32, 0x5f, 0x9c, 0x1e, 0xaf, 0xf4, 0x4a, 0x57, 0x60,
	0x62, 0x4f, 0xb5, 0xbb, 0xf8, 0xf6, 0x09, 0x79, 0xaa, 0x26, 0xee, 0x00, 0x81, 0x32, 0x12, 0x28,
	0x58, 0x0b, 0xe6, 0x45, 0x7e, 0x3c, 0x98, 0x06, 0xdb, 0x8f, 0x71, 0x6b, 0x5e, 0x11, 0x6b, 0xb8,
	0x36, 0xc8, 0xfc, 0xc8, 0x8f, 0xbd, 0xc6, 0x58, 0x42, 0xc7, 0xa4, 0x2f, 0x0c, 0xa6, 0x85, 0xde,
	0x18, 0xd6, 0x76, 0x6c, 0x4f, 0x18, 0x9c, 0xeb, 0x8d, 0xb1, 0x01, 0xf0, 0x7d, 0x10, 0x44, 0x7e,
	0x1c, 0x34, 0x01, 0xf0, 0x3a, 0xb8, 0x24, 0x07, 0xc0, 0xb9, 0x30, 0x26, 0x45, 0x58, 0x64, 0x82,
	0x75, 0x9c, 0xd7, 0x87, 0xb5, 0x79, 0xb0, 0xc2, 0x09, 0xa5, 0x5a, 0x8a, 0x57, 0xd6, 0xfd, 0x1f,
	0xde, 0x5b, 0x41, 0x27, 0x64, 0xb4, 0x0f, 0x73, 0x28, 0x50, 0xa2, 0xd4, 0x8a, 0xf5, 0x9c, 0xf8,
	0xb0, 0xb6, 0xb3, 0x46, 0xd2, 0x73, 0xd2, 0x43, 0xb9, 0x16, 0x69, 0x69, 0x58, 0xdf, 0xf9, 0x43,
	0xd7, 0xc2, 0x47, 0x43, 0xcf, 0x48, 0xb7, 0x28, 0x55, 0x0a, 0xc8, 0x06, 0xce, 0x2d, 0x9d, 0xa2,
	0x54, 0xb7, 0x48, 0xaf, 0x49, 0x9f, 0x3f, 0xcb, 0x6c, 0x59, 0x08, 0xc5, 0x48, 0xd4, 0x8e, 0x87,
	0x37, 0xa3, 0xc4, 0xae, 0x3c, 0xf9, 0x5b, 0xec, 0xfc, 0xb7, 0x98, 0x5e, 0x6d, 0x77, 0xa1, 0xf7,
	0xbe, 0x0b, 0xbd, 0xcf, 0x5d, 0xe8, 0xbd, 0x7d, 0x85, 0x2d, 0x72, 0xc2, 0xf5, 0x3a, 0xc9, 0xa5,
	0x5a, 0x71, 0xc8, 0x13, 0x94, 0xcb, 0x45, 0x35, 0x3d, 0xf3, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x57, 0x01, 0xb4, 0xf8, 0xcc, 0x01, 0x00, 0x00,
}
