// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: visual_plan.proto

package tipb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import encoding_binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TaskType int32

const (
	TaskType_unknown  TaskType = 0
	TaskType_root     TaskType = 1
	TaskType_cop      TaskType = 2
	TaskType_batchCop TaskType = 3
	TaskType_mpp      TaskType = 4
)

var TaskType_name = map[int32]string{
	0: "unknown",
	1: "root",
	2: "cop",
	3: "batchCop",
	4: "mpp",
}
var TaskType_value = map[string]int32{
	"unknown":  0,
	"root":     1,
	"cop":      2,
	"batchCop": 3,
	"mpp":      4,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}
func (TaskType) EnumDescriptor() ([]byte, []int) { return fileDescriptorVisualPlan, []int{0} }

type StoreType int32

const (
	StoreType_unspecified StoreType = 0
	StoreType_tidb        StoreType = 1
	StoreType_tikv        StoreType = 2
	StoreType_tiflash     StoreType = 3
)

var StoreType_name = map[int32]string{
	0: "unspecified",
	1: "tidb",
	2: "tikv",
	3: "tiflash",
}
var StoreType_value = map[string]int32{
	"unspecified": 0,
	"tidb":        1,
	"tikv":        2,
	"tiflash":     3,
}

func (x StoreType) String() string {
	return proto.EnumName(StoreType_name, int32(x))
}
func (StoreType) EnumDescriptor() ([]byte, []int) { return fileDescriptorVisualPlan, []int{1} }

type DriverSide int32

const (
	DriverSide_empty     DriverSide = 0
	DriverSide_build     DriverSide = 1
	DriverSide_probe     DriverSide = 2
	DriverSide_seed      DriverSide = 3
	DriverSide_recursive DriverSide = 4
)

var DriverSide_name = map[int32]string{
	0: "empty",
	1: "build",
	2: "probe",
	3: "seed",
	4: "recursive",
}
var DriverSide_value = map[string]int32{
	"empty":     0,
	"build":     1,
	"probe":     2,
	"seed":      3,
	"recursive": 4,
}

func (x DriverSide) String() string {
	return proto.EnumName(DriverSide_name, int32(x))
}
func (DriverSide) EnumDescriptor() ([]byte, []int) { return fileDescriptorVisualPlan, []int{2} }

type VisualData struct {
	Main             *VisualOperator   `protobuf:"bytes,1,opt,name=main" json:"main,omitempty"`
	Ctes             []*VisualOperator `protobuf:"bytes,2,rep,name=ctes" json:"ctes,omitempty"`
	WithRuntimeStats bool              `protobuf:"varint,3,opt,name=with_runtime_stats,json=withRuntimeStats,proto3" json:"with_runtime_stats,omitempty"`
}

func (m *VisualData) Reset()                    { *m = VisualData{} }
func (m *VisualData) String() string            { return proto.CompactTextString(m) }
func (*VisualData) ProtoMessage()               {}
func (*VisualData) Descriptor() ([]byte, []int) { return fileDescriptorVisualPlan, []int{0} }

func (m *VisualData) GetMain() *VisualOperator {
	if m != nil {
		return m.Main
	}
	return nil
}

func (m *VisualData) GetCtes() []*VisualOperator {
	if m != nil {
		return m.Ctes
	}
	return nil
}

func (m *VisualData) GetWithRuntimeStats() bool {
	if m != nil {
		return m.WithRuntimeStats
	}
	return false
}

type VisualOperator struct {
	// The children of the current operator
	Children []*VisualOperator `protobuf:"bytes,1,rep,name=children" json:"children,omitempty"`
	// the name of the current operator
	Name       string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DriverSide DriverSide `protobuf:"varint,3,opt,name=driver_side,json=driverSide,proto3,enum=tipb.DriverSide" json:"driver_side,omitempty"`
	// the cost of the current operator
	// runtime stats available: cost means real cost
	// runtime stats unavailable: cost means est_cost
	Cost      float64   `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
	EstRows   float64   `protobuf:"fixed64,5,opt,name=est_rows,json=estRows,proto3" json:"est_rows,omitempty"`
	ActRows   uint64    `protobuf:"varint,6,opt,name=act_rows,json=actRows,proto3" json:"act_rows,omitempty"`
	TaskType  TaskType  `protobuf:"varint,7,opt,name=task_type,json=taskType,proto3,enum=tipb.TaskType" json:"task_type,omitempty"`
	StoreType StoreType `protobuf:"varint,8,opt,name=store_type,json=storeType,proto3,enum=tipb.StoreType" json:"store_type,omitempty"`
	// The XXXReader/XXXScan/MemTable/PointGet/BatchPointGet may use this
	AccessTable       string   `protobuf:"bytes,9,opt,name=access_table,json=accessTable,proto3" json:"access_table,omitempty"`
	AccessIndex       string   `protobuf:"bytes,10,opt,name=access_index,json=accessIndex,proto3" json:"access_index,omitempty"`
	AccessPartition   string   `protobuf:"bytes,11,opt,name=access_partition,json=accessPartition,proto3" json:"access_partition,omitempty"`
	OperatorInfo      string   `protobuf:"bytes,12,opt,name=operator_info,json=operatorInfo,proto3" json:"operator_info,omitempty"`
	RootBasicExecInfo string   `protobuf:"bytes,13,opt,name=root_basic_exec_info,json=rootBasicExecInfo,proto3" json:"root_basic_exec_info,omitempty"`
	RootGroupExecInfo []string `protobuf:"bytes,14,rep,name=root_group_exec_info,json=rootGroupExecInfo" json:"root_group_exec_info,omitempty"`
	CopExecInfo       string   `protobuf:"bytes,15,opt,name=cop_exec_info,json=copExecInfo,proto3" json:"cop_exec_info,omitempty"`
	MemoryBytes       int64    `protobuf:"varint,16,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes         int64    `protobuf:"varint,17,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
}

func (m *VisualOperator) Reset()                    { *m = VisualOperator{} }
func (m *VisualOperator) String() string            { return proto.CompactTextString(m) }
func (*VisualOperator) ProtoMessage()               {}
func (*VisualOperator) Descriptor() ([]byte, []int) { return fileDescriptorVisualPlan, []int{1} }

func (m *VisualOperator) GetChildren() []*VisualOperator {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *VisualOperator) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VisualOperator) GetDriverSide() DriverSide {
	if m != nil {
		return m.DriverSide
	}
	return DriverSide_empty
}

func (m *VisualOperator) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *VisualOperator) GetEstRows() float64 {
	if m != nil {
		return m.EstRows
	}
	return 0
}

func (m *VisualOperator) GetActRows() uint64 {
	if m != nil {
		return m.ActRows
	}
	return 0
}

func (m *VisualOperator) GetTaskType() TaskType {
	if m != nil {
		return m.TaskType
	}
	return TaskType_unknown
}

func (m *VisualOperator) GetStoreType() StoreType {
	if m != nil {
		return m.StoreType
	}
	return StoreType_unspecified
}

func (m *VisualOperator) GetAccessTable() string {
	if m != nil {
		return m.AccessTable
	}
	return ""
}

func (m *VisualOperator) GetAccessIndex() string {
	if m != nil {
		return m.AccessIndex
	}
	return ""
}

func (m *VisualOperator) GetAccessPartition() string {
	if m != nil {
		return m.AccessPartition
	}
	return ""
}

func (m *VisualOperator) GetOperatorInfo() string {
	if m != nil {
		return m.OperatorInfo
	}
	return ""
}

func (m *VisualOperator) GetRootBasicExecInfo() string {
	if m != nil {
		return m.RootBasicExecInfo
	}
	return ""
}

func (m *VisualOperator) GetRootGroupExecInfo() []string {
	if m != nil {
		return m.RootGroupExecInfo
	}
	return nil
}

func (m *VisualOperator) GetCopExecInfo() string {
	if m != nil {
		return m.CopExecInfo
	}
	return ""
}

func (m *VisualOperator) GetMemoryBytes() int64 {
	if m != nil {
		return m.MemoryBytes
	}
	return 0
}

func (m *VisualOperator) GetDiskBytes() int64 {
	if m != nil {
		return m.DiskBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*VisualData)(nil), "tipb.VisualData")
	proto.RegisterType((*VisualOperator)(nil), "tipb.VisualOperator")
	proto.RegisterEnum("tipb.TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("tipb.StoreType", StoreType_name, StoreType_value)
	proto.RegisterEnum("tipb.DriverSide", DriverSide_name, DriverSide_value)
}
func (m *VisualData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VisualData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Main != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(m.Main.Size()))
		n1, err := m.Main.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Ctes) > 0 {
		for _, msg := range m.Ctes {
			dAtA[i] = 0x12
			i++
			i = encodeVarintVisualPlan(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.WithRuntimeStats {
		dAtA[i] = 0x18
		i++
		if m.WithRuntimeStats {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *VisualOperator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VisualOperator) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Children) > 0 {
		for _, msg := range m.Children {
			dAtA[i] = 0xa
			i++
			i = encodeVarintVisualPlan(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.DriverSide != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(m.DriverSide))
	}
	if m.Cost != 0 {
		dAtA[i] = 0x21
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Cost))))
		i += 8
	}
	if m.EstRows != 0 {
		dAtA[i] = 0x29
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.EstRows))))
		i += 8
	}
	if m.ActRows != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(m.ActRows))
	}
	if m.TaskType != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(m.TaskType))
	}
	if m.StoreType != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(m.StoreType))
	}
	if len(m.AccessTable) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.AccessTable)))
		i += copy(dAtA[i:], m.AccessTable)
	}
	if len(m.AccessIndex) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.AccessIndex)))
		i += copy(dAtA[i:], m.AccessIndex)
	}
	if len(m.AccessPartition) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.AccessPartition)))
		i += copy(dAtA[i:], m.AccessPartition)
	}
	if len(m.OperatorInfo) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.OperatorInfo)))
		i += copy(dAtA[i:], m.OperatorInfo)
	}
	if len(m.RootBasicExecInfo) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.RootBasicExecInfo)))
		i += copy(dAtA[i:], m.RootBasicExecInfo)
	}
	if len(m.RootGroupExecInfo) > 0 {
		for _, s := range m.RootGroupExecInfo {
			dAtA[i] = 0x72
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.CopExecInfo) > 0 {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(len(m.CopExecInfo)))
		i += copy(dAtA[i:], m.CopExecInfo)
	}
	if m.MemoryBytes != 0 {
		dAtA[i] = 0x80
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(m.MemoryBytes))
	}
	if m.DiskBytes != 0 {
		dAtA[i] = 0x88
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintVisualPlan(dAtA, i, uint64(m.DiskBytes))
	}
	return i, nil
}

func encodeVarintVisualPlan(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *VisualData) Size() (n int) {
	var l int
	_ = l
	if m.Main != nil {
		l = m.Main.Size()
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	if len(m.Ctes) > 0 {
		for _, e := range m.Ctes {
			l = e.Size()
			n += 1 + l + sovVisualPlan(uint64(l))
		}
	}
	if m.WithRuntimeStats {
		n += 2
	}
	return n
}

func (m *VisualOperator) Size() (n int) {
	var l int
	_ = l
	if len(m.Children) > 0 {
		for _, e := range m.Children {
			l = e.Size()
			n += 1 + l + sovVisualPlan(uint64(l))
		}
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	if m.DriverSide != 0 {
		n += 1 + sovVisualPlan(uint64(m.DriverSide))
	}
	if m.Cost != 0 {
		n += 9
	}
	if m.EstRows != 0 {
		n += 9
	}
	if m.ActRows != 0 {
		n += 1 + sovVisualPlan(uint64(m.ActRows))
	}
	if m.TaskType != 0 {
		n += 1 + sovVisualPlan(uint64(m.TaskType))
	}
	if m.StoreType != 0 {
		n += 1 + sovVisualPlan(uint64(m.StoreType))
	}
	l = len(m.AccessTable)
	if l > 0 {
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	l = len(m.AccessIndex)
	if l > 0 {
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	l = len(m.AccessPartition)
	if l > 0 {
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	l = len(m.OperatorInfo)
	if l > 0 {
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	l = len(m.RootBasicExecInfo)
	if l > 0 {
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	if len(m.RootGroupExecInfo) > 0 {
		for _, s := range m.RootGroupExecInfo {
			l = len(s)
			n += 1 + l + sovVisualPlan(uint64(l))
		}
	}
	l = len(m.CopExecInfo)
	if l > 0 {
		n += 1 + l + sovVisualPlan(uint64(l))
	}
	if m.MemoryBytes != 0 {
		n += 2 + sovVisualPlan(uint64(m.MemoryBytes))
	}
	if m.DiskBytes != 0 {
		n += 2 + sovVisualPlan(uint64(m.DiskBytes))
	}
	return n
}

func sovVisualPlan(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozVisualPlan(x uint64) (n int) {
	return sovVisualPlan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VisualData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVisualPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VisualData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VisualData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Main", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Main == nil {
				m.Main = &VisualOperator{}
			}
			if err := m.Main.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ctes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ctes = append(m.Ctes, &VisualOperator{})
			if err := m.Ctes[len(m.Ctes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithRuntimeStats", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithRuntimeStats = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipVisualPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVisualPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VisualOperator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVisualPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VisualOperator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VisualOperator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Children", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Children = append(m.Children, &VisualOperator{})
			if err := m.Children[len(m.Children)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DriverSide", wireType)
			}
			m.DriverSide = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DriverSide |= (DriverSide(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Cost = float64(math.Float64frombits(v))
		case 5:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field EstRows", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.EstRows = float64(math.Float64frombits(v))
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActRows", wireType)
			}
			m.ActRows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActRows |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskType", wireType)
			}
			m.TaskType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskType |= (TaskType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreType", wireType)
			}
			m.StoreType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreType |= (StoreType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessTable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessTable = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessPartition", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessPartition = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootBasicExecInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootBasicExecInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootGroupExecInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootGroupExecInfo = append(m.RootGroupExecInfo, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CopExecInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVisualPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CopExecInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryBytes", wireType)
			}
			m.MemoryBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryBytes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskBytes", wireType)
			}
			m.DiskBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiskBytes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVisualPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVisualPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVisualPlan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVisualPlan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVisualPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthVisualPlan
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowVisualPlan
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipVisualPlan(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthVisualPlan = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVisualPlan   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("visual_plan.proto", fileDescriptorVisualPlan) }

var fileDescriptorVisualPlan = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xcd, 0x6e, 0xeb, 0x36,
	0x10, 0x85, 0x43, 0x4b, 0x89, 0xa5, 0xf1, 0x1f, 0x43, 0xa4, 0x80, 0x5a, 0xa0, 0x86, 0x92, 0x6e,
	0x9c, 0xb4, 0x70, 0xda, 0x74, 0xdd, 0x45, 0xd3, 0xb4, 0x45, 0x56, 0x0d, 0x94, 0xa0, 0x5b, 0x81,
	0xa2, 0x68, 0x9b, 0xb0, 0x25, 0x12, 0x24, 0x6d, 0xc7, 0x2f, 0x91, 0x75, 0x1f, 0xa9, 0xcb, 0xfb,
	0x08, 0x17, 0xb9, 0x2f, 0x72, 0x41, 0xca, 0x76, 0x9c, 0x45, 0x76, 0x07, 0xe7, 0x7c, 0x33, 0x43,
	0x8a, 0x03, 0xc1, 0xe9, 0x4a, 0x98, 0x25, 0x5d, 0xe4, 0x6a, 0x41, 0xeb, 0xb1, 0xd2, 0xd2, 0x4a,
	0x12, 0x5a, 0xa1, 0x8a, 0xef, 0xce, 0xa6, 0x72, 0x2a, 0xbd, 0x71, 0xed, 0x54, 0x93, 0x5d, 0xbc,
	0x20, 0x80, 0x7f, 0x7d, 0xc5, 0x1d, 0xb5, 0x94, 0x8c, 0x20, 0xac, 0xa8, 0xa8, 0x13, 0x94, 0xa2,
	0x51, 0xe7, 0xe6, 0x6c, 0xec, 0x2a, 0xc7, 0x4d, 0xfe, 0x8f, 0xe2, 0x9a, 0x5a, 0xa9, 0x33, 0x4f,
	0x38, 0x92, 0x59, 0x6e, 0x92, 0x56, 0x1a, 0x7c, 0x4c, 0x3a, 0x82, 0xfc, 0x04, 0x64, 0x2d, 0xec,
	0x2c, 0xd7, 0xcb, 0xda, 0x8a, 0x8a, 0xe7, 0xc6, 0x52, 0x6b, 0x92, 0x20, 0x45, 0xa3, 0x28, 0xc3,
	0x2e, 0xc9, 0x9a, 0xe0, 0xd1, 0xf9, 0x17, 0x2f, 0xc7, 0xd0, 0x7f, 0xdf, 0x86, 0xfc, 0x0c, 0x11,
	0x9b, 0x89, 0x45, 0xa9, 0xb9, 0x3b, 0xd8, 0xc7, 0xe3, 0xf6, 0x14, 0x21, 0x10, 0xd6, 0xb4, 0xe2,
	0x49, 0x2b, 0x45, 0xa3, 0x38, 0xf3, 0x9a, 0xfc, 0x02, 0x9d, 0x52, 0x8b, 0x15, 0xd7, 0xb9, 0x11,
	0x25, 0xf7, 0xf3, 0xfb, 0x37, 0xb8, 0x69, 0x74, 0xe7, 0x83, 0x47, 0x51, 0xf2, 0x0c, 0xca, 0xbd,
	0x76, 0x6d, 0x98, 0x34, 0x36, 0x09, 0x53, 0x34, 0x42, 0x99, 0xd7, 0xe4, 0x5b, 0x88, 0xb8, 0xb1,
	0xb9, 0x96, 0x6b, 0x93, 0x1c, 0x7b, 0xbf, 0xcd, 0x8d, 0xcd, 0xe4, 0xda, 0xb8, 0x88, 0xb2, 0x6d,
	0x74, 0x92, 0xa2, 0x51, 0x98, 0xb5, 0x29, 0x6b, 0xa2, 0x1f, 0x21, 0xb6, 0xd4, 0xcc, 0x73, 0xbb,
	0x51, 0x3c, 0x69, 0xfb, 0xd1, 0xfd, 0x66, 0xf4, 0x13, 0x35, 0xf3, 0xa7, 0x8d, 0xe2, 0x59, 0x64,
	0xb7, 0x8a, 0x8c, 0x01, 0x8c, 0x95, 0x9a, 0x37, 0x74, 0xe4, 0xe9, 0x41, 0x43, 0x3f, 0x3a, 0xdf,
	0xe3, 0xb1, 0xd9, 0x49, 0x72, 0x0e, 0x5d, 0xca, 0x18, 0x37, 0x26, 0xb7, 0xb4, 0x58, 0xf0, 0x24,
	0xf6, 0xb7, 0xee, 0x34, 0xde, 0x93, 0xb3, 0x0e, 0x10, 0x51, 0x97, 0xfc, 0x39, 0x81, 0x43, 0xe4,
	0xde, 0x59, 0xe4, 0x12, 0xf0, 0x16, 0x51, 0x54, 0x5b, 0x61, 0x85, 0xac, 0x93, 0x8e, 0xc7, 0x06,
	0x8d, 0xff, 0xb0, 0xb3, 0xc9, 0x0f, 0xd0, 0x93, 0xdb, 0x8f, 0x9e, 0x8b, 0x7a, 0x22, 0x93, 0xae,
	0xe7, 0xba, 0x3b, 0xf3, 0xbe, 0x9e, 0x48, 0x72, 0x0d, 0x67, 0x5a, 0x4a, 0x9b, 0x17, 0xd4, 0x08,
	0x96, 0xf3, 0x67, 0xce, 0x1a, 0xb6, 0xe7, 0xd9, 0x53, 0x97, 0xdd, 0xba, 0xe8, 0xcf, 0x67, 0xce,
	0xde, 0x15, 0x4c, 0xb5, 0x5c, 0xaa, 0x83, 0x82, 0x7e, 0x1a, 0xec, 0x0a, 0xfe, 0x76, 0xd1, 0xbe,
	0xe0, 0x02, 0x7a, 0x4c, 0x1e, 0x92, 0x83, 0xe6, 0x56, 0x4c, 0xbe, 0x31, 0xe7, 0xd0, 0xad, 0x78,
	0x25, 0xf5, 0x26, 0x2f, 0x36, 0x6e, 0x5d, 0x71, 0x8a, 0x46, 0x41, 0xd6, 0x69, 0xbc, 0x5b, 0x67,
	0x91, 0xef, 0x01, 0x4a, 0x61, 0xe6, 0x5b, 0xe0, 0xd4, 0x03, 0xb1, 0x73, 0x7c, 0x7c, 0xf5, 0x3b,
	0x44, 0xbb, 0x37, 0x22, 0x1d, 0x68, 0x2f, 0xeb, 0x79, 0x2d, 0xd7, 0x35, 0x3e, 0x22, 0x11, 0x84,
	0xee, 0x4c, 0x18, 0x91, 0x36, 0x04, 0x4c, 0x2a, 0xdc, 0x22, 0x5d, 0x88, 0x0a, 0x6a, 0xd9, 0xec,
	0x0f, 0xa9, 0x70, 0xe0, 0xec, 0x4a, 0x29, 0x1c, 0x5e, 0xfd, 0x06, 0xf1, 0xfe, 0xe1, 0xc8, 0x00,
	0x3a, 0xcb, 0xda, 0x28, 0xce, 0xc4, 0x44, 0xf0, 0xb2, 0xe9, 0x63, 0x45, 0x59, 0x60, 0xd4, 0xa8,
	0xf9, 0x0a, 0xb7, 0xdc, 0x20, 0x2b, 0x26, 0x0b, 0x6a, 0x66, 0x38, 0xb8, 0xfa, 0x0b, 0xe0, 0x6d,
	0x41, 0x49, 0x0c, 0xc7, 0xbc, 0x52, 0x76, 0x83, 0x8f, 0x9c, 0x2c, 0x96, 0x62, 0x51, 0x62, 0xe4,
	0xa4, 0xd2, 0xb2, 0xe0, 0xb8, 0xe5, 0xba, 0x18, 0xce, 0x4b, 0x1c, 0x90, 0x1e, 0xc4, 0x9a, 0xb3,
	0xa5, 0x36, 0x62, 0xc5, 0x71, 0x78, 0x7b, 0xf9, 0xff, 0xeb, 0x10, 0x7d, 0x7a, 0x1d, 0xa2, 0xcf,
	0xaf, 0x43, 0xf4, 0xdf, 0x97, 0xe1, 0x11, 0x7c, 0xc3, 0x64, 0x35, 0x56, 0xa2, 0x9e, 0x32, 0xaa,
	0xc6, 0xee, 0x10, 0x7e, 0xcb, 0x1e, 0x50, 0x71, 0xe2, 0xff, 0x0e, 0xbf, 0x7e, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xb4, 0x9f, 0xd7, 0x39, 0x4e, 0x04, 0x00, 0x00,
}
